# Generated by Django 3.0.4 on 2020-03-31 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=35)),
                ('last_updated', models.DateTimeField()),
                ('date_created', models.DateTimeField()),
                ('update_state', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Runs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('percentage', models.IntegerField()),
                ('transaction_count', models.IntegerField()),
                ('date_time', models.DateTimeField()),
            ],
        ),
    ]
