# Generated by Django 3.0.4 on 2020-04-01 17:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address',
            name='id',
        ),
        migrations.AddField(
            model_name='runs',
            name='address',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='search.Address'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='address',
            name='address',
            field=models.CharField(max_length=35, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='address',
            name='date_created',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='address',
            name='update_state',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='runs',
            name='date_time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
